# Generated by Django 5.2.1 on 2025-06-14 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_hash', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Behavioral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typing_speed', models.FloatField(blank=True, null=True)),
                ('mouse_entropy', models.FloatField(blank=True, null=True)),
                ('keystroke_dynamics', models.JSONField(blank=True, default=dict, null=True)),
                ('scroll_behavior', models.JSONField(blank=True, default=dict, null=True)),
                ('url_changes', models.JSONField(blank=True, default=list, null=True)),
                ('time_of_visit_patterns', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('build_id', models.CharField(blank=True, max_length=100, null=True)),
                ('private_mode', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('webgl_hash', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSSMediaFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefers_dark_scheme', models.BooleanField(blank=True, null=True)),
                ('font_smoothing', models.BooleanField(blank=True, null=True)),
                ('reduced_motion', models.BooleanField(blank=True, null=True)),
                ('reduced_data', models.BooleanField(blank=True, null=True)),
                ('forced_colors', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_height', models.IntegerField(blank=True, null=True)),
                ('screen_width', models.IntegerField(blank=True, null=True)),
                ('color_depth', models.IntegerField(blank=True, null=True)),
                ('device_pixel_ratio', models.FloatField(blank=True, null=True)),
                ('color_gamut', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedMediaCapabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdm_list', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fonts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_fonts', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Graphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webgl_renderer', models.TextField(blank=True, null=True)),
                ('webgl_vendor', models.TextField(blank=True, null=True)),
                ('webgl_extensions', models.JSONField(blank=True, default=list, null=True)),
                ('webgpu_adapter', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(blank=True, max_length=200, null=True)),
                ('cpu_cores', models.IntegerField(blank=True, null=True)),
                ('device_memory', models.FloatField(blank=True, null=True)),
                ('device_architecture', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HttpHeaderFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_count', models.IntegerField(blank=True, null=True)),
                ('http_version', models.CharField(blank=True, max_length=20, null=True)),
                ('tls_protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('tls_cipher_suite', models.CharField(blank=True, max_length=100, null=True)),
                ('headers_present', models.JSONField(blank=True, default=list, null=True)),
                ('unusual_headers', models.JSONField(blank=True, default=list, null=True)),
                ('referer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_codecs', models.JSONField(blank=True, default=list, null=True)),
                ('video_codecs', models.JSONField(blank=True, default=list, null=True)),
                ('media_devices', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_type', models.CharField(blank=True, max_length=20, null=True)),
                ('downlink', models.FloatField(blank=True, null=True)),
                ('rtt', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timings', models.JSONField(blank=True, default=dict, null=True)),
                ('memory', models.JSONField(blank=True, default=dict, null=True)),
                ('network_timing', models.JSONField(blank=True, default=dict, null=True)),
                ('framerate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation', models.CharField(blank=True, max_length=20, null=True)),
                ('notifications', models.CharField(blank=True, max_length=20, null=True)),
                ('camera', models.CharField(blank=True, max_length=20, null=True)),
                ('microphone', models.CharField(blank=True, max_length=20, null=True)),
                ('midi', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plugins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_plugins', models.JSONField(blank=True, default=list, null=True)),
                ('mime_types', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies_enabled', models.BooleanField(blank=True, null=True)),
                ('storage_estimate', models.JSONField(blank=True, default=dict, null=True)),
                ('service_workers', models.JSONField(blank=True, default=list, null=True)),
                ('indexeddb_dbs', models.JSONField(blank=True, default=list, null=True)),
                ('cache_storage_keys', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone_offset', models.IntegerField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TouchPointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_touch_points', models.IntegerField(blank=True, null=True)),
                ('pointer_fine', models.BooleanField(blank=True, null=True)),
                ('standalone', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.audio')),
                ('behavioral', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.behavioral')),
                ('browser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.browser')),
                ('canvas', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.canvas')),
                ('css_media_feature', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.cssmediafeature')),
                ('display', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.display')),
                ('encrypted_media_capabilities', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.encryptedmediacapabilities')),
                ('fonts', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.fonts')),
                ('graphics', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.graphics')),
                ('hardware', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.hardware')),
                ('http_header', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.httpheaderfingerprint')),
                ('ip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.ip')),
                ('media', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.media')),
                ('network_connection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.networkconnection')),
                ('performance_timings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.performancetimings')),
                ('permissions_status', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.permissionsstatus')),
                ('plugins', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.plugins')),
                ('storage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.storage')),
                ('time_zone', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.timezone')),
                ('touch_pointer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprint.touchpointer')),
            ],
        ),
    ]
